replicaCount: 1

image:
  repository: todo-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

backend:
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  automount: false

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false
